export const studyPrograms: Array<{ value: string, label: string }> = [
    { value: 'bachelor-bioinformatik', label: 'Bachelor Bioinformatik' },
    { value: 'bachelor-elektrotechnik-informationstechnik', label: 'Bachelor Elektrotechnik Informationstechnik' },
    { value: 'bachelor-informatik', label: 'Bachelor Informatik' },
    { value: 'bachelor-informatik-games-engineering', label: 'Bachelor Informatik Games Engineering' },
    { value: 'bachelor-information-engineering', label: 'Bachelor Information Engineering' },
    { value: 'bachelor-mathematik', label: 'Bachelor Mathematik' },
    { value: 'bachelor-wirtschaftsinformatik', label: 'Bachelor Wirtschaftsinformatik' },
    { value: 'master-bioinformatik', label: 'Master Bioinformatik' },
    { value: 'master-biomedical-computing', label: 'Master Biomedical Computing' },
    { value: 'master-communications-electronics-engineering', label: 'Master Communications Electronics Engineering' },
    { value: 'master-computational-science-engineering', label: 'Master Computational Science Engineering' },
    { value: 'master-data-engineering-analytics', label: 'Master Data Engineering Analytics' },
    { value: 'master-elektrotechnik-informationstechnik', label: 'Master Elektrotechnik Informationstechnik' },
    { value: 'master-informatik', label: 'Master Informatik' },
    { value: 'master-informatik-games-engineering', label: 'Master Informatik Games Engineering' },
    { value: 'master-information-engineering', label: 'Master Information Engineering' },
    { value: 'master-information-systems', label: 'Master Information Systems' },
    { value: 'master-mathematical-finance-actuarial-science', label: 'Master Mathematical Finance Actuarial Science' },
    { value: 'master-mathematics-data-science', label: 'Master Mathematics Data Science' },
    { value: 'master-mathematics-operations-research', label: 'Master Mathematics Operations Research' },
    { value: 'master-mathematics-science-engineering', label: 'Master Mathematics Science Engineering' },
    { value: 'master-mathematik', label: 'Master Mathematik' },
    { value: 'master-neuroengineering', label: 'Neuroengineering' },
    { value: 'master-robotics-cognition-intelligence', label: 'Master Robotics Cognition Intelligence' },
    { value: 'master-topmath', label: 'TopMath' }
];